### PR TITLE
Update LeClient.cs

### PR DESCRIPTION
**Pull request by KieranOBrien-R7**
updating API endpoint to point towards data.logentries.com and also updating the PORTS to reflect recent changes on Logentries.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks - this looks fine. Do you have a pointer to any relevant LogEntries announcement/doc that we can leave here in this thread for reference?

**Comment by nblumhardt** [comment]
(Just a note, there was some churn in the golang client around this - https://github.com/logentries/le_node/issues/64 - not sure what the status is.)

**Comment by nblumhardt** [comment]
@erendrake no idea, unfortunately. Is it broken for you? Thanks!

**Comment by aarndt** [comment]
Any plans to merge this in? This PR is over a year old. The code currently references api.logentries.com, which does not match up to the documentation at https://docs.logentries.com/docs/input-token

Additionally, ports 10000 and 20000 are blocked by our firewall, and we would benefit from sending over 80/443, as configured in this pull request. 

Thanks!

**Comment by nblumhardt** [comment]
@aarndt thanks for the note. I left this initially because it seemed the changes might not be universally compatible, and not using Logentries myself I'm unable to test. Merging now as 3.0, please let me know if the new package works for you.

**Comment by aarndt** [comment]
Thank you @nblumhardt, seems to work great! I appreciate your quick response 👍

**Comment by nblumhardt** [comment]
Thanks for the feedback @aarndt 👍

**Pull request merged**
